/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author shinee
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private boolean casilla[][] = new boolean[3][3];
    private int matriz[][] = new int[3][3];
    private String turno = "usuario1";
    private String usuario1, usuario2;
    private int vecesGano1 = 0, vecesGano2 = 0, vecesEmpate = 0;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal(String usuario1, String usuario2) {
        this.usuario1 = usuario1;
        this.usuario2 = usuario2;
        
        initComponents();
        setSize(600,600);
        setLocationRelativeTo(null);
        llenarCasillas();
        llenarMatriz();
    }
    
    private void llenarCasillas(){
        for(int i=0; i<3; i++){
            for(int j=0; j<3;j++){
                casilla[i][j] = true;
            }
        }
    }
    
    private void llenarMatriz(){
        for(int i=0; i<3; i++){
            for(int j=0; j<3; j++){
                matriz[i][j] = 0;
            }
        }
    }
    
    private void dibujarX(JButton boton){
        boton.setIcon(new ImageIcon(getClass().getResource("/imagenes/cerrar.png")));
    }
    
    private void dibujarO(JButton boton){
        boton.setIcon(new ImageIcon(getClass().getResource("/imagenes/circulo.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.ABORT
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        btnArribaIzq = new javax.swing.JButton();
        btnArriba = new javax.swing.JButton();
        btnArribaDer = new javax.swing.JButton();
        btnIzquierda = new javax.swing.JButton();
        btnCentro = new javax.swing.JButton();
        btnDerecha = new javax.swing.JButton();
        btnAbajoIzq = new javax.swing.JButton();
        btnAbajo = new javax.swing.JButton();
        btnAbajoDer = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuJuego = new javax.swing.JMenu();
        comenzarDeNuevo = new javax.swing.JMenuItem();
        mostrarResultados = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        salir = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setLayout(new java.awt.GridLayout(3, 3));

        btnArribaIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArribaIzqActionPerformed(evt);
            }
        });
        panel.add(btnArribaIzq);

        btnArriba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArribaActionPerformed(evt);
            }
        });
        panel.add(btnArriba);

        btnArribaDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArribaDerActionPerformed(evt);
            }
        });
        panel.add(btnArribaDer);

        btnIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzquierdaActionPerformed(evt);
            }
        });
        panel.add(btnIzquierda);

        btnCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCentroActionPerformed(evt);
            }
        });
        panel.add(btnCentro);

        btnDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerechaActionPerformed(evt);
            }
        });
        panel.add(btnDerecha);

        btnAbajoIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbajoIzqActionPerformed(evt);
            }
        });
        panel.add(btnAbajoIzq);

        btnAbajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbajoActionPerformed(evt);
            }
        });
        panel.add(btnAbajo);

        btnAbajoDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbajoDerActionPerformed(evt);
            }
        });
        panel.add(btnAbajoDer);

        menuJuego.setText("Juego");
        menuJuego.setFont(new java.awt.Font("Chandas", 0, 14)); // NOI18N

        comenzarDeNuevo.setFont(new java.awt.Font("Chandas", 0, 12)); // NOI18N
        comenzarDeNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon.png"))); // NOI18N
        comenzarDeNuevo.setText("Comenzar de nuevo");
        comenzarDeNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comenzarDeNuevoActionPerformed(evt);
            }
        });
        menuJuego.add(comenzarDeNuevo);

        mostrarResultados.setFont(new java.awt.Font("Chandas", 0, 10)); // NOI18N
        mostrarResultados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tabla.png"))); // NOI18N
        mostrarResultados.setText("Mostrar resultados");
        mostrarResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarResultadosActionPerformed(evt);
            }
        });
        menuJuego.add(mostrarResultados);
        menuJuego.add(jSeparator1);

        salir.setFont(new java.awt.Font("Chandas", 0, 10)); // NOI18N
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        menuJuego.add(salir);

        jMenuBar1.add(menuJuego);

        menuAyuda.setText("Ayuda");
        menuAyuda.setFont(new java.awt.Font("Chandas", 0, 14)); // NOI18N
        menuAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAyudaMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void btnArribaIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArribaIzqActionPerformed
        if(casilla[0][0] == true){ // verificación de si se ha dado click
            if(turno.equals("usuario1")){ // verificación turno
                dibujarX(btnArribaIzq);
                matriz[0][0] = 1;
                turno = "usuario2";
            }else{
            dibujarO(btnArribaIzq);
            matriz[0][0] = 2;
            turno = "usuario1";
            }
            
            casilla[0][0] = false;
            comprobarGanador();
        } 
       
    }//GEN-LAST:event_btnArribaIzqActionPerformed

    private void btnArribaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArribaActionPerformed
       if(casilla[0][1] == true){
           if(turno.equals("usuario1")){
               dibujarX(btnArriba);
               matriz[0][1] = 1;
               turno = "usuario2";
           }else{
               dibujarO(btnArriba);
               matriz[0][1] = 2;
               turno = "usuario1";
           }
      
           casilla[0][1] = false;
           comprobarGanador();
       }
    }//GEN-LAST:event_btnArribaActionPerformed

    private void btnArribaDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArribaDerActionPerformed
        if(casilla[0][2] == true){
            if(turno.equals("usuario1")){
                dibujarX(btnArribaDer);
                matriz[0][2] = 1;
                turno = "usuario2";
            }else{
                dibujarO(btnArribaDer);
                matriz[0][2] = 2;
                turno = "usuario1";
            }
            
            casilla[0][2] = false;
            comprobarGanador();
        }
        
    }//GEN-LAST:event_btnArribaDerActionPerformed

    private void btnIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzquierdaActionPerformed
        if(casilla [1][0] == true){
            if(turno.equals("usuario1")){
                dibujarX(btnIzquierda);
                matriz[1][0] = 1;
                turno = "usuario2";
            }else{
                dibujarO(btnIzquierda);
                matriz[1][0] = 2;
                turno = "usuario1";
            }
            
            casilla [1][0] = false;
            comprobarGanador();
        }
    }//GEN-LAST:event_btnIzquierdaActionPerformed

    private void btnCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCentroActionPerformed
        if(casilla [1][1] == true){
            if(turno.equals("usuario1")){
                dibujarX(btnCentro);
                matriz[1][1] = 1;
                turno = "usuario2";
            }else{
                dibujarO(btnCentro);
                matriz[1][1] = 2;
                turno = "usuario1";
            }
            
            casilla [1][1] = false;
            comprobarGanador();
        }
    }//GEN-LAST:event_btnCentroActionPerformed

    private void btnDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerechaActionPerformed
        if(casilla [1][2] == true){
            if(turno.equals("usuario1")){
                dibujarX(btnDerecha);
                matriz[1][2] = 1;
                turno = "usuario2";
            }else{
                dibujarO(btnDerecha);
                matriz[1][2] = 2;
                turno = "usuario1";
            }
            
            casilla [1][2] = false;
            comprobarGanador();
        }
    }//GEN-LAST:event_btnDerechaActionPerformed

    private void btnAbajoIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbajoIzqActionPerformed
        if(casilla [2][0] == true){
            if(turno.equals("usuario1")){
                dibujarX(btnAbajoIzq);
                matriz[2][0] = 1;
                turno = "usuario2";
            }else{
                dibujarO(btnAbajoIzq);
                matriz[2][0] = 2;
                turno = "usuario1";
            }
            
            casilla [2][0] = false;
            comprobarGanador();
        }
    }//GEN-LAST:event_btnAbajoIzqActionPerformed

    private void btnAbajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbajoActionPerformed
        if(casilla [2][1] == true){
            if(turno.equals("usuario1")){
                dibujarX(btnAbajo);
                matriz[2][1] = 1;
                turno = "usuario2";
            }else{
                dibujarO(btnAbajo);
                matriz[2][1] = 2;
                turno = "usuario1";
            }
            
            casilla [2][1] = false;
            comprobarGanador();
        }
    }//GEN-LAST:event_btnAbajoActionPerformed

    private void btnAbajoDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbajoDerActionPerformed
        if(casilla [2][2] == true){
            if(turno.equals("usuario1")){
                dibujarX(btnAbajoDer);
                matriz[2][2] = 1;
                turno = "usuario2";
            }else{
                dibujarO(btnAbajoDer);
                matriz[2][2] = 2;
                turno = "usuario1";
            }
            
            casilla [2][2] = false;
            comprobarGanador();
        }
    }//GEN-LAST:event_btnAbajoDerActionPerformed

    private void mostrarResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarResultadosActionPerformed
       VentanaMostrarRespuestas ventanaMR = new VentanaMostrarRespuestas(this, true,usuario1,usuario2,vecesGano1,vecesGano2,vecesEmpate);
       ventanaMR.setVisible(true);
    }//GEN-LAST:event_mostrarResultadosActionPerformed

    private void comenzarDeNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comenzarDeNuevoActionPerformed
        vecesGano1 = 0;vecesGano2 = 0; vecesEmpate = 0;
        reiniciarJuego();
    }//GEN-LAST:event_comenzarDeNuevoActionPerformed

    private void menuAyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAyudaMouseClicked
        try {
            Desktop.getDesktop().browse(new URI("https://www.guiainfantil.com/articulos/ocio/juegos/juego-de-tres-en-raya-como-jugar-con-los-ninos-con-papel-y-lapiz/"));
        } catch (URISyntaxException | IOException ex) {
            //Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        //Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        
    }//GEN-LAST:event_menuAyudaMouseClicked
    private void comprobarGanador(){
        boolean ganador1 = false;
        boolean ganador2 = false;
        int casillasEmpate = 0;
        
        ganador1 = comprobar(1);
        ganador2 = comprobar(2);
        
        if(ganador1 == true){
           vecesGano1++;
           VentanaGanador ventanaG = new VentanaGanador(this, true, usuario1);
           ventanaG.setVisible(true);
           reiniciarJuego();
        }else if(ganador2 == true){
            vecesGano2++;
            VentanaGanador ventanaG = new VentanaGanador(this, true, usuario2);
            ventanaG.setVisible(true);
            reiniciarJuego();
        }else{
            for (int i = 0; i < 3; i++) {
                for (int j = 0; j < 3; j++) {
                    if(matriz[i][j] != 0){
                        casillasEmpate++;
                    }
                }
            }
            
            if(casillasEmpate == 9){
                vecesEmpate++;
                VentanaEmpate ventanaE = new VentanaEmpate(this, true);
                ventanaE.setVisible(true);
                reiniciarJuego();
            }else{
                casillasEmpate = 0;
            }
        }
        
    }
    
    private boolean comprobar(int num){
        boolean ganador = false;
        
        if(matriz[0][0] == num && matriz[0][1] == num && matriz[0][2] == num ){
            ganador = true;
        }else if(matriz[1][0] == num && matriz[1][1] == num && matriz[1][2] == num ){
            ganador = true;
        }else if(matriz[2][0] == num && matriz[2][1] == num && matriz[2][2] == num ){
            ganador = true;
        }else if(matriz[0][0] == num && matriz[1][1] == num && matriz[2][2] == num ){
            ganador = true;
        }else if(matriz[0][2] == num && matriz[1][1] == num && matriz[2][0] == num ){
            ganador = true;
        }else if(matriz[0][0] == num && matriz[1][0] == num && matriz[2][0] == num ){
            ganador = true;
        }else if(matriz[0][1] == num && matriz[1][1] == num && matriz[2][1] == num ){
            ganador = true;
        }else if(matriz[0][2] == num && matriz[1][2] == num && matriz[2][2] == num ){
            ganador = true;
        }
        
        return ganador;
    }
    
    private void reiniciarJuego(){
        llenarCasillas();
        llenarMatriz();
        
        btnAbajo.setIcon(null);
        btnAbajoDer.setIcon(null);
        btnAbajoIzq.setIcon(null);
        btnArribaDer.setIcon(null);
        btnArriba.setIcon(null);
        btnArribaIzq.setIcon(null);
        btnCentro.setIcon(null);
        btnDerecha.setIcon(null);
        btnIzquierda.setIcon(null);
        
        quienJuegaPrimero();
    }
    
    private void quienJuegaPrimero(){
        VentanaQuienJuega vqj = new VentanaQuienJuega(this, true, usuario1, usuario2);
        vqj.setVisible(true);
        turno = vqj.getTurno();
    }
    
    
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbajo;
    private javax.swing.JButton btnAbajoDer;
    private javax.swing.JButton btnAbajoIzq;
    private javax.swing.JButton btnArriba;
    private javax.swing.JButton btnArribaDer;
    private javax.swing.JButton btnArribaIzq;
    private javax.swing.JButton btnCentro;
    private javax.swing.JButton btnDerecha;
    private javax.swing.JButton btnIzquierda;
    private javax.swing.JMenuItem comenzarDeNuevo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuJuego;
    private javax.swing.JMenuItem mostrarResultados;
    private javax.swing.JPanel panel;
    private javax.swing.JMenuItem salir;
    // End of variables declaration//GEN-END:variables
}
